services:

  # Postgres
  postgres:
    platform: linux/amd64
    image: postgres:16-alpine
    volumes:
      - ./init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: rpg
      POSTGRES_PASSWORD: rpg
      POSTGRES_DB: rpg

  # OpenTelemetry Collector
  otel-collector:
    platform: linux/amd64
    image: otel/opentelemetry-collector:0.105.0
    volumes:
      - ./otel-collector.yaml:/etc/otel-collector.yaml
    command:
      - --config=/etc/otel-collector.yaml
    ports:
      - "4318:4318"    # OTLP HTTP receiver
    depends_on:
      - jaeger
      - prometheus

  # Jaeger
  jaeger:
    platform: linux/amd64
    image: jaegertracing/all-in-one:1.58.1
    ports:
      - "16686:16686"  # Jaeger web interface

  # Loki
  loki:
    platform: linux/amd64
    image: grafana/loki:3.1.0
    volumes:
      - ./loki.yaml:/etc/loki.yaml
    command: -config.file=/etc/loki.yaml


  # Tempo
  tempo:
    image: grafana/tempo:2.5.0
    platform: linux/amd64
    volumes:
      - ./tempo.yaml:/etc/tempo.yaml
    command:
      - -config.file=/etc/tempo.yaml

  # Prometheus
  prometheus:
    platform: linux/amd64
    image: prom/prometheus:v2.53.1
    volumes:
      - ./prometheus.yaml:/etc/prometheus.yaml
    command:
      - --config.file=/etc/prometheus.yaml
      - --web.enable-remote-write-receiver
    ports:
      - "9090:9090"    # Prometheus web interface

  # Grafana
  grafana:
    image: grafana/grafana-oss:11.1.0
    platform: linux/amd64
    volumes:
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/grafana-datasources.yaml:ro
      - ./grafana-dashboards.yaml:/etc/grafana/provisioning/dashboards/grafana-dashboards.yaml:ro
      - ../common/dashboards/JVM.json:/var/lib/grafana/dashboards/JVM.json:ro
      - ../common/dashboards/HTTP-server-instances.json:/var/lib/grafana/dashboards/HTTP-server-instances.json:ro
      - ../common/dashboards/HTTP-server-routes.json:/var/lib/grafana/dashboards/HTTP-server-routes.json:ro
      - ../common/dashboards/HTTP-client.json:/var/lib/grafana/dashboards/HTTP-client.json:ro
      - ./dashboards/overview.json:/var/lib/grafana/dashboards/overview.json:ro
      - ./dashboards/sentences-and-words.json:/var/lib/grafana/dashboards/sentences-and-words.json:ro
    environment:
      - GF_ANALYTICS_REPORTING_ENABLED=false
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/var/lib/grafana/dashboards/overview.json
      - GF_NEWS_NEWS_FEED_ENABLED=false
    ports:
      - "3001:3000"       # Grafana web interface
    depends_on:
      - loki
      - tempo
      - prometheus

